### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by PpEeIi** [jasonlinuxzhang/zhangyou_bova#1]
By not providing "FindZED.cmake" in CMAKE_MODULE_PATH this project has
 asked CMake to find a package configuration file provided by "ZED", but
 CMake did not find one.

My computer configuration ：Opencv 3.3.0 cuda8.0 cudnn5.1

I don't have a ZED camera.

**Comment by PpEeIi** [comment]
你是中国学生吧，我也是，这里为什么要找ZED这个配置文件，因为拟用的ZED的相机吗，我用的不是ZED，是因为这个原因吗？

**Comment by jasonlinuxzhang** [comment]
你可以在cmakelist.txt中将zed相关的配置去掉，我之前用到zed，但是后面就没用了，cmakelist.txt就没改过来，我代码里直接用的左右图片来计算视差的。

**Comment by jasonlinuxzhang** [comment]
你可以根据main.cpp里的用法来修改自己的程序，main.cpp里写的逻辑很简单。

**Comment by PpEeIi** [comment]
仅仅是操作cmakelist注释没有用，我对c++并不熟悉，注释完了cmake ..会报错

**Comment by PpEeIi** [comment]
CMake Error at CMakeLists.txt:62 (cuda_add_executable):
 Unknown CMake command "cuda_add_executable".
按理说这个命令不应该被识别为未知命令啊

**Comment by bjerr** [comment]
我也遇到了同样的问题 请问有解决嘛
