### ISSUE TITLE
How to set some params compared with StereoSGBM in OpenCV？？

### ISSUE THREAD

**Issue by Micalson** [jasonlinuxzhang/zhangyou_bova#2]
Zhang, hello! Thank you for your codes for sgm_cuda. A questions bothered me, and I hope your answers. In StereoSGBM from OpenCV, it can set the param called minDisparity, but I can not find the corresponding param. I think this parameter is very important, so could you explain it for me? The following image is something about StereoSGBM from OpenCV.
![sgbm](https://user-images.githubusercontent.com/45941423/51165353-e545ba00-18da-11e9-9cf1-e8e75ef92258.png)

**Comment by Micalson** [comment]
@jasonlinuxzhang

**Comment by jasonlinuxzhang** [comment]
Sorry, Micalson, I didn't set the variable to change the minDisparity. I fixed the minDisparity to 0.

**Comment by Micalson** [comment]
I think this variable could be negative in some stereo vision system, so could you tell me why did you fix this to zero? @jasonlinuxzhang

**Comment by jasonlinuxzhang** [comment]
Why do you think the value of minDisparity can be negative? The x(col) of a point in the left picture should be smaller than the picture on the right. When we look for similar points, if we are based on the left side, the points in the right picture must be on the left side of the left picture. The range of similar points we look for is from x-minDisparity to x-maxDisparity. Therefore, minDisparity should be greater than 0. I fixed it to 0 to measure long distances. If you set minDisparity to a larger number, you cannot measure long distances. @Micalson

**Comment by Micalson** [comment]
Well,  beautiful explanation. Thank you very much. if so, this project is very valueable and deserves more stars. Good luck to you. @jasonlinuxzhang

**Comment by Micalson** [comment]
Hi, Zhang! again me. I find that the minDisparity could be negative by experiments. In my stereo system, the angle between the optical axis of the cameras is 20 degrees. Because of the angle,  while the measured object is beyond the the intersection of the two optical axis, the minDisparity could be negative. You can try it.

**Comment by Micalson** [comment]
@jasonlinuxzhang
